repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args: ["--tab-width", "4"]
        types: [markdown]
      - id: prettier
        exclude_types: [markdown]
